spring.application.name=JPDwebSwp
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/cloneJpdweb}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}

spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.port=9090
server.servlet.session.timeout=20m

# Firebase
firebase.storage.bucket=firebasestorage.app
firebase.config.path=firebase-service-account.json

# PayPal
paypal.client.id=${PAYPAL_CLIENT_ID:}
paypal.client.secret=${PAYPAL_CLIENT_SECRET:}
paypal.mode=sandbox

# OpenAI & Gemini API Keys
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
gemini.api.key=${GEMINI_API_KEY:}
openai.api.key=${OPENAI_API_KEY:}

# Security OAuth2 (Keycloak)
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/jpdweb/protocol/openid-connect/certs

creator.withdraw.minimize_amount=20.0
